from typing import Final

SHELVE_DATABASE_NAME: Final[str] = "database"

DEFAULT_MINIMUM_ATTENDANCE_RATE_PERCENTAGE: Final[float] = 0.5
DEFAULT_SNAPSHOT_INTERVAL_SECONDS: Final[int] = 3

MAXMIMUM_EMBEDS_PER_MESSAGE: Final[int] = 10
MAXMIMUM_EMBED_DESCRIPTION_LENGTH: Final[int] = 3_000
