from typing import Final

SHELVE_DATABASE_NAME: Final[str] = "database"

DEFAULT_MINIMUM_ATTENDANCE_RATE_PERCENTAGE: Final[float] = 0.5
DEFAULT_SNAPSHOT_INTERVAL_SECONDS: Final[int] = 3
DEFAULT_AUTO_CLEAR_SNAPSHOTS_ON_NEW_SESSION: Final[bool] = False
DEFAULT_AUTO_CLEAR_SNAPSHOTS_AFTER_ATTENDANCE_REPORT: Final[bool] = False
DEFAULT_IMPORTANT_ATTENDANCE_RESPONSES_ARE_EPHEMERAL: Final[bool] = True

MAXMIMUM_EMBEDS_PER_MESSAGE: Final[int] = 10
MAXMIMUM_EMBED_DESCRIPTION_LENGTH: Final[int] = 3_000

CSV_HEADERS: Final[str] = "user_id,in_attendance"

MYSTBIN_BASE_API: Final[str] = "https://api.mystb.in"
MYSTBIN_PASTE_API: Final[str] = f"{MYSTBIN_BASE_API}/paste"

BUTTON_VIEW_TIMEOUT: Final[int] = 300
