from typing import Final

SHELVE_DATABASE_NAME: Final[str] = "database"

DEFAULT_MINIMUM_ATTENDANCE_RATE_PERCENTAGE: Final[float] = 0.5
DEFAULT_SNAPSHOT_INTERVAL_SECONDS: Final[int] = 3
DEFAULT_AUTO_CLEAR_SNAPSHOTS_ON_NEW_SESSION: Final[bool] = False
DEFAULT_AUTO_CLEAR_SNAPSHOTS_AFTER_ATTENDANCE_REPORT: Final[bool] = False

MAXMIMUM_EMBEDS_PER_MESSAGE: Final[int] = 10
MAXMIMUM_EMBED_DESCRIPTION_LENGTH: Final[int] = 3_000
